version: "3"
services:
  web:
    image: michelav/counter:latest 
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "7000:80"
    networks:
      - countnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "7777:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - countnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - countnet
    command: redis-server --appendonly yes
networks:
  countnet: